- name: Executing main playbook
  hosts: glue_jobs
  vars_files:
    - "{{ vars_file }}"
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  become: yes
  roles:
    - name: gluejob
