#- name: Run roles with custom and localhost inventories
#  hosts: localhost
#  become: yes
#  roles:
#    - role: lambda

#- name: Run role on localhost
# hosts: localhost
 # vars:
#    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
#  roles:
    - role: crawler

#- name: Run role on localhost
#  hosts: localhost
#  vars:
#    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
#  roles:
 #   - role: s3


 

