- name: Run roles with custom and localhost inventories
  hosts: localhost
  become: yes
  roles:
    - name: lambda

- name: Run role on localhost
  hosts: localhost
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  roles:
    - name: crawler

- name: Run role on localhost
  hosts: localhost
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  roles:
    - name: s3

- name: Executing main playbook
  hosts: glue_jobs
  vars_files:
    - "{{ vars_file }}"
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  become: yes
  roles:
    - name: gluejob

