---
- name: Run roles with custom and localhost inventories
  hosts: localhost
  vars_files:
    - ./vars.yaml  # Replace with the actual path to shared_vars.yml
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  roles:
    - name: lambda

- name: Run role on localhost for Glue Crawler
  hosts: localhost
  vars_files:
    - ./vars.yaml
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  roles:
    - name: crawler

- name: Run role on localhost for S3
  hosts: localhost
  vars_files:
    - ./vars.yaml
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  roles:
    - name: s3

- name: Executing main playbook for Glue Jobs
  hosts: glue_jobs
  vars_files:
    - ./vars.yaml
    - "{{ vars_file }}"  # If you have additional vars to include
  vars:
    ansible_python_interpreter: /root/.pyenv/versions/3.11.8/bin/python
  become: yes
  roles:
    - name: gluejob

