#- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
 # scm: git
  #version: main
  #name: lambda

#- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
#  scm: git
#  version: main
#  name: crawler

#- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
#  scm: git
#  version: main
#  name: s3

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  scm: git
  version: main
  name: ansible/roles/gluejob 

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  version: main
  name: lambda
  scm: git
  path: ansible/roles/lambda

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  version: main
  name: crawler
  scm: git
  path: ansible/roles/crawler

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  version: main
  name: s3
  scm: git
  path: ansible/roles/s3
