- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  scm: git
  version: main
  name: gluejob

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  scm: git
  version: main
  name: lambda

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  scm: git
  version: main
  name: crawler

- src: https://github.com/satuluriakhil420/ens-ent-360-dsc
  scm: git
  version: main
  name: s3
 
